// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GooglePlayConstants
{
        public const string achievement_s_30 = "CgkImPiAiL0UEAIQDQ"; // <GPGSID>
        public const string achievement_win_with_life_50 = "CgkImPiAiL0UEAIQEg"; // <GPGSID>
        public const string achievement_lose_30 = "CgkImPiAiL0UEAIQEQ"; // <GPGSID>
        public const string achievement_s_board_winner = "CgkImPiAiL0UEAIQBg"; // <GPGSID>
        public const string leaderboard_best_time__l_level = "CgkImPiAiL0UEAIQBA"; // <GPGSID>
        public const string leaderboard_best_time__s_level = "CgkImPiAiL0UEAIQAg"; // <GPGSID>
        public const string achievement_m_20 = "CgkImPiAiL0UEAIQDg"; // <GPGSID>
        public const string leaderboard_highest_scores = "CgkImPiAiL0UEAIQAQ"; // <GPGSID>
        public const string achievement_l_board_winner = "CgkImPiAiL0UEAIQCA"; // <GPGSID>
        public const string achievement_use_30_life = "CgkImPiAiL0UEAIQFA"; // <GPGSID>
        public const string achievement_rank_60_go_custom = "CgkImPiAiL0UEAIQFg"; // <GPGSID>
        public const string achievement_l_10 = "CgkImPiAiL0UEAIQDw"; // <GPGSID>
        public const string achievement_xl_5 = "CgkImPiAiL0UEAIQEA"; // <GPGSID>
        public const string achievement_lose = "CgkImPiAiL0UEAIQDA"; // <GPGSID>
        public const string leaderboard_best_time__m_level = "CgkImPiAiL0UEAIQAw"; // <GPGSID>
        public const string achievement_rank_120_or_pro_sykwalker = "CgkImPiAiL0UEAIQFw"; // <GPGSID>
        public const string achievement_win = "CgkImPiAiL0UEAIQCw"; // <GPGSID>
        public const string achievement_m_board_winner = "CgkImPiAiL0UEAIQBw"; // <GPGSID>
        public const string leaderboard_best_time__xl_level = "CgkImPiAiL0UEAIQBQ"; // <GPGSID>
        public const string achievement_xl_board_winner = "CgkImPiAiL0UEAIQCQ"; // <GPGSID>
        public const string achievement_ads_40_or_pro = "CgkImPiAiL0UEAIQEw"; // <GPGSID>
        public const string achievement_rank_30_go_xl = "CgkImPiAiL0UEAIQFQ"; // <GPGSID>

}

